name: Build Macast Windows with Latest mpv

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller requests

      - name: 下载最新 mpv
        shell: pwsh
        run: |
          $mpv_api = "https://api.github.com/repos/mpv-player/mpv/releases/latest"
          $release = Invoke-RestMethod -Uri $mpv_api
          $asset = $release.assets | Where-Object { $_.name -like "*win64*.zip" } | Select-Object -First 1
          Invoke-WebRequest -Uri $asset.browser_download_url -OutFile mpv-latest.zip
          Expand-Archive mpv-latest.zip -DestinationPath mpv
          # 假设 Macast 的 mpv 放在 macast/player/mpv/ 目录
          Copy-Item mpv/*/* "macast/player/mpv/" -Recurse -Force

      - name: 打包 Macast
        run: |
          pyinstaller --noconfirm --onefile --name Macast-Windows main.py

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: Macast-Windows
          path: dist/Macast-Windows.exe
